using Microsoft.EntityFrameworkCore;
using YoFi.V3.Data;
using YoFi.V3.Entities.Tenancy.Models;

namespace YoFi.V3.Tests.Integration.Data;

/// <summary>
/// Integration tests for UserTenantRoleAssignment entity and related database operations.
/// These tests verify role assignment functionality, constraints, and relationships.
/// </summary>
public class UserTenantRoleAssignmentTests
{
    private ApplicationDbContext _context;
    private DbContextOptions<ApplicationDbContext> _options;
    private Tenant _tenant1;
    private Tenant _tenant2;

    [SetUp]
    public async Task Setup()
    {
        // Use in-memory database for testing
        _options = new DbContextOptionsBuilder<ApplicationDbContext>()
            .UseSqlite("DataSource=:memory:")
            .Options;

        _context = new ApplicationDbContext(_options);
        _context.Database.OpenConnection(); // Keep in-memory DB alive
        _context.Database.EnsureCreated();

        // Create test tenants
        _tenant1 = new Tenant { Name = "Tenant 1", Description = "First test tenant" };
        _tenant2 = new Tenant { Name = "Tenant 2", Description = "Second test tenant" };
        _context.Tenants.AddRange(_tenant1, _tenant2);
        await _context.SaveChangesAsync();
    }

    [TearDown]
    public void TearDown()
    {
        _context.Database.CloseConnection();
        _context.Dispose();
    }

    [Test]
    public async Task UserTenantRoleAssignment_HasCorrectTableName()
    {
        // Given: A role assignment
        var assignment = new UserTenantRoleAssignment
        {
            UserId = "user123",
            TenantId = _tenant1.Id,
            Role = TenantRole.Editor
        };

        _context.UserTenantRoleAssignments.Add(assignment);
        await _context.SaveChangesAsync();

        // When: Checking the table name in the database
        var connection = _context.Database.GetDbConnection();
        await connection.OpenAsync();
        using var command = connection.CreateCommand();
        command.CommandText = "SELECT name FROM sqlite_master WHERE type='table' AND name='YoFi.V3.UserTenantRoleAssignments'";
        var tableName = await command.ExecuteScalarAsync();

        // Then: The table should exist with the correct name
        Assert.That(tableName, Is.EqualTo("YoFi.V3.UserTenantRoleAssignments"));
    }

    [Test]
    public async Task UserTenantRoleAssignment_IdIsAutoGenerated()
    {
        // Given: A role assignment without Id set
        var assignment = new UserTenantRoleAssignment
        {
            UserId = "user123",
            TenantId = _tenant1.Id,
            Role = TenantRole.Editor
        };

        Assert.That(assignment.Id, Is.EqualTo(0)); // Initially zero

        // When: Adding and saving the assignment
        _context.UserTenantRoleAssignments.Add(assignment);
        await _context.SaveChangesAsync();

        // Then: Id should be auto-generated
        Assert.That(assignment.Id, Is.GreaterThan(0));
    }

    [Test]
    public async Task UserTenantRoleAssignment_UserIdCanBeEmpty()
    {
        // Given: An assignment with empty UserId (allowed at DB level)
        var assignment = new UserTenantRoleAssignment
        {
            UserId = string.Empty,
            TenantId = _tenant1.Id,
            Role = TenantRole.Editor
        };

        _context.UserTenantRoleAssignments.Add(assignment);

        // When: Saving the assignment
        await _context.SaveChangesAsync();

        // Then: Should be saved successfully (validation should happen at application level)
        Assert.That(assignment.Id, Is.GreaterThan(0));
    }

    [Test]
    public async Task UserTenantRoleAssignment_TenantIdForeignKeyConstraint()
    {
        // Given: An assignment with non-existent TenantId
        var assignment = new UserTenantRoleAssignment
        {
            UserId = "user123",
            TenantId = 999999, // Non-existent tenant
            Role = TenantRole.Editor
        };

        _context.UserTenantRoleAssignments.Add(assignment);

        // When/Then: Saving should fail due to foreign key constraint
        Assert.ThrowsAsync<DbUpdateException>(async () => await _context.SaveChangesAsync());
    }

    [Test]
    public async Task UserTenantRoleAssignment_RoleIsStoredAsString()
    {
        // Given: A role assignment with an enum role
        var assignment = new UserTenantRoleAssignment
        {
            UserId = "user123",
            TenantId = _tenant1.Id,
            Role = TenantRole.Owner
        };

        _context.UserTenantRoleAssignments.Add(assignment);
        await _context.SaveChangesAsync();

        // When: Checking the stored value in the database
        var connection = _context.Database.GetDbConnection();
        await connection.OpenAsync();
        using var command = connection.CreateCommand();
        command.CommandText = "SELECT Role FROM \"YoFi.V3.UserTenantRoleAssignments\" WHERE Id = @id";
        var parameter = command.CreateParameter();
        parameter.ParameterName = "@id";
        parameter.Value = assignment.Id;
        command.Parameters.Add(parameter);
        var roleValue = await command.ExecuteScalarAsync();

        // Then: Role should be stored as string "Owner"
        Assert.That(roleValue, Is.EqualTo("Owner"));
    }

    [Test]
    public async Task UserTenantRoleAssignment_AllRolesCanBeStored()
    {
        // Given: Assignments with all role types
        var assignments = new[]
        {
            new UserTenantRoleAssignment { UserId = "user1", TenantId = _tenant1.Id, Role = TenantRole.Viewer },
            new UserTenantRoleAssignment { UserId = "user2", TenantId = _tenant1.Id, Role = TenantRole.Editor },
            new UserTenantRoleAssignment { UserId = "user3", TenantId = _tenant1.Id, Role = TenantRole.Owner }
        };

        _context.UserTenantRoleAssignments.AddRange(assignments);
        await _context.SaveChangesAsync();

        // When: Retrieving the assignments
        var retrieved = await _context.UserTenantRoleAssignments
            .Where(a => a.TenantId == _tenant1.Id)
            .OrderBy(a => a.UserId)
            .ToListAsync();

        // Then: All roles should be correctly stored and retrieved
        Assert.That(retrieved, Has.Count.EqualTo(3));
        Assert.That(retrieved.Select(r => r.Role), Is.EquivalentTo(new[] { TenantRole.Viewer, TenantRole.Editor, TenantRole.Owner }));
    }

    [Test]
    public async Task UserTenantRoleAssignment_UniqueConstraintPerUserAndTenant()
    {
        // Given: A role assignment for a user and tenant
        var assignment1 = new UserTenantRoleAssignment
        {
            UserId = "user123",
            TenantId = _tenant1.Id,
            Role = TenantRole.Editor
        };

        _context.UserTenantRoleAssignments.Add(assignment1);
        await _context.SaveChangesAsync();

        // When: Trying to add another assignment for the same user and tenant
        var assignment2 = new UserTenantRoleAssignment
        {
            UserId = "user123",
            TenantId = _tenant1.Id,
            Role = TenantRole.Owner // Different role, same user and tenant
        };

        _context.UserTenantRoleAssignments.Add(assignment2);

        // Then: Should fail due to unique constraint
        Assert.ThrowsAsync<DbUpdateException>(async () => await _context.SaveChangesAsync());
    }

    [Test]
    public async Task UserTenantRoleAssignment_SameUserCanHaveDifferentRolesInDifferentTenants()
    {
        // Given: A user with roles in multiple tenants
        var assignment1 = new UserTenantRoleAssignment
        {
            UserId = "user123",
            TenantId = _tenant1.Id,
            Role = TenantRole.Editor
        };
        var assignment2 = new UserTenantRoleAssignment
        {
            UserId = "user123",
            TenantId = _tenant2.Id,
            Role = TenantRole.Owner
        };

        _context.UserTenantRoleAssignments.AddRange(assignment1, assignment2);
        await _context.SaveChangesAsync();

        // When: Retrieving assignments for the user
        var userAssignments = await _context.UserTenantRoleAssignments
            .Where(a => a.UserId == "user123")
            .ToListAsync();

        // Then: Should have both assignments with different roles
        Assert.That(userAssignments, Has.Count.EqualTo(2));
        Assert.That(userAssignments.Select(a => a.TenantId), Is.EquivalentTo(new[] { _tenant1.Id, _tenant2.Id }));
    }

    [Test]
    public async Task UserTenantRoleAssignment_CanQueryByUserId()
    {
        // Given: Multiple role assignments
        _context.UserTenantRoleAssignments.AddRange(
            new UserTenantRoleAssignment { UserId = "user123", TenantId = _tenant1.Id, Role = TenantRole.Editor },
            new UserTenantRoleAssignment { UserId = "user456", TenantId = _tenant1.Id, Role = TenantRole.Viewer },
            new UserTenantRoleAssignment { UserId = "user123", TenantId = _tenant2.Id, Role = TenantRole.Owner }
        );
        await _context.SaveChangesAsync();

        // When: Querying by UserId
        var user123Assignments = await _context.UserTenantRoleAssignments
            .Where(a => a.UserId == "user123")
            .ToListAsync();

        // Then: Should return all assignments for that user
        Assert.That(user123Assignments, Has.Count.EqualTo(2));
        Assert.That(user123Assignments.All(a => a.UserId == "user123"), Is.True);
    }

    [Test]
    public async Task UserTenantRoleAssignment_CanQueryByTenantId()
    {
        // Given: Multiple role assignments
        _context.UserTenantRoleAssignments.AddRange(
            new UserTenantRoleAssignment { UserId = "user123", TenantId = _tenant1.Id, Role = TenantRole.Editor },
            new UserTenantRoleAssignment { UserId = "user456", TenantId = _tenant1.Id, Role = TenantRole.Viewer },
            new UserTenantRoleAssignment { UserId = "user789", TenantId = _tenant2.Id, Role = TenantRole.Owner }
        );
        await _context.SaveChangesAsync();

        // When: Querying by TenantId
        var tenant1Assignments = await _context.UserTenantRoleAssignments
            .Where(a => a.TenantId == _tenant1.Id)
            .ToListAsync();

        // Then: Should return all assignments for that tenant
        Assert.That(tenant1Assignments, Has.Count.EqualTo(2));
        Assert.That(tenant1Assignments.All(a => a.TenantId == _tenant1.Id), Is.True);
    }

    [Test]
    public async Task UserTenantRoleAssignment_CanBeUpdated()
    {
        // Given: An existing role assignment
        var assignment = new UserTenantRoleAssignment
        {
            UserId = "user123",
            TenantId = _tenant1.Id,
            Role = TenantRole.Viewer
        };
        _context.UserTenantRoleAssignments.Add(assignment);
        await _context.SaveChangesAsync();
        var id = assignment.Id;

        // When: Updating the role
        assignment.Role = TenantRole.Editor;
        await _context.SaveChangesAsync();

        // Then: Change should be persisted
        var updated = await _context.UserTenantRoleAssignments.FindAsync(id);
        Assert.That(updated, Is.Not.Null);
        Assert.That(updated!.Role, Is.EqualTo(TenantRole.Editor));
    }

    [Test]
    public async Task UserTenantRoleAssignment_CanBeDeleted()
    {
        // Given: An existing role assignment
        var assignment = new UserTenantRoleAssignment
        {
            UserId = "user123",
            TenantId = _tenant1.Id,
            Role = TenantRole.Editor
        };
        _context.UserTenantRoleAssignments.Add(assignment);
        await _context.SaveChangesAsync();
        var id = assignment.Id;

        // When: Deleting the assignment
        _context.UserTenantRoleAssignments.Remove(assignment);
        await _context.SaveChangesAsync();

        // Then: Assignment should be removed from database
        var deleted = await _context.UserTenantRoleAssignments.FindAsync(id);
        Assert.That(deleted, Is.Null);
    }

    [Test]
    public async Task UserTenantRoleAssignment_NavigationPropertyToTenant()
    {
        // Given: A role assignment
        var assignment = new UserTenantRoleAssignment
        {
            UserId = "user123",
            TenantId = _tenant1.Id,
            Role = TenantRole.Editor
        };
        _context.UserTenantRoleAssignments.Add(assignment);
        await _context.SaveChangesAsync();

        // When: Loading assignment with tenant navigation property
        var retrieved = await _context.UserTenantRoleAssignments
            .Include(a => a.Tenant)
            .FirstAsync(a => a.Id == assignment.Id);

        // Then: Navigation property should be populated
        Assert.That(retrieved.Tenant, Is.Not.Null);
        Assert.That(retrieved.Tenant!.Id, Is.EqualTo(_tenant1.Id));
        Assert.That(retrieved.Tenant.Name, Is.EqualTo(_tenant1.Name));
    }

    [Test]
    public async Task UserTenantRoleAssignment_CascadeDeleteWhenTenantDeleted()
    {
        // Given: A tenant with role assignments
        var assignment = new UserTenantRoleAssignment
        {
            UserId = "user123",
            TenantId = _tenant1.Id,
            Role = TenantRole.Editor
        };
        _context.UserTenantRoleAssignments.Add(assignment);
        await _context.SaveChangesAsync();
        var assignmentId = assignment.Id;

        // When: Deleting the tenant
        _context.Tenants.Remove(_tenant1);
        await _context.SaveChangesAsync();

        // Then: Role assignment should be cascade deleted
        var deletedAssignment = await _context.UserTenantRoleAssignments.FindAsync(assignmentId);
        Assert.That(deletedAssignment, Is.Null);
    }

    [Test]
    public async Task UserTenantRoleAssignment_CanQueryUserRoleForSpecificTenant()
    {
        // Given: A user with roles in multiple tenants
        _context.UserTenantRoleAssignments.AddRange(
            new UserTenantRoleAssignment { UserId = "user123", TenantId = _tenant1.Id, Role = TenantRole.Editor },
            new UserTenantRoleAssignment { UserId = "user123", TenantId = _tenant2.Id, Role = TenantRole.Owner }
        );
        await _context.SaveChangesAsync();

        // When: Querying for user's role in a specific tenant
        var assignment = await _context.UserTenantRoleAssignments
            .FirstOrDefaultAsync(a => a.UserId == "user123" && a.TenantId == _tenant1.Id);

        // Then: Should return the correct assignment
        Assert.That(assignment, Is.Not.Null);
        Assert.That(assignment!.Role, Is.EqualTo(TenantRole.Editor));
    }

    [Test]
    public async Task UserTenantRoleAssignment_UserIdMaxLengthConfigured()
    {
        // Given: An assignment with UserId exceeding the configured max length (450 chars)
        var longUserId = new string('A', 451);
        var assignment = new UserTenantRoleAssignment
        {
            UserId = longUserId,
            TenantId = _tenant1.Id,
            Role = TenantRole.Editor
        };

        _context.UserTenantRoleAssignments.Add(assignment);
        await _context.SaveChangesAsync();

        // When: Retrieving the assignment
        var retrieved = await _context.UserTenantRoleAssignments.FindAsync(assignment.Id);

        // Then: SQLite doesn't enforce max length by default, but the configuration exists
        // Application-level validation should prevent this scenario
        Assert.That(retrieved, Is.Not.Null);
        Assert.That(retrieved!.UserId, Is.EqualTo(longUserId));
    }

    [Test]
    public async Task UserTenantRoleAssignment_MultipleUsersCanHaveSameRoleInTenant()
    {
        // Given: Multiple users with the same role in a tenant
        var assignments = new[]
        {
            new UserTenantRoleAssignment { UserId = "user1", TenantId = _tenant1.Id, Role = TenantRole.Editor },
            new UserTenantRoleAssignment { UserId = "user2", TenantId = _tenant1.Id, Role = TenantRole.Editor },
            new UserTenantRoleAssignment { UserId = "user3", TenantId = _tenant1.Id, Role = TenantRole.Editor }
        };

        _context.UserTenantRoleAssignments.AddRange(assignments);
        await _context.SaveChangesAsync();

        // When: Querying for Editor role in tenant
        var editors = await _context.UserTenantRoleAssignments
            .Where(a => a.TenantId == _tenant1.Id && a.Role == TenantRole.Editor)
            .ToListAsync();

        // Then: Should return all editors
        Assert.That(editors, Has.Count.EqualTo(3));
    }
}
