using Microsoft.EntityFrameworkCore;
using YoFi.V3.Data;
using YoFi.V3.Entities.Models;

namespace YoFi.V3.Tests.Integration.Data;

/// <summary>
/// Tests specific to WeatherForecast entity functionality.
/// General database/IDataProvider tests are in SimpleTests.cs
/// </summary>
public class WeatherForecastTests
{
    private ApplicationDbContext _context;
    private DbContextOptions<ApplicationDbContext> _options;

    [SetUp]
    public void Setup()
    {
        // Use in-memory database for testing
        _options = new DbContextOptionsBuilder<ApplicationDbContext>()
            .UseSqlite("DataSource=:memory:")
            .Options;

        _context = new ApplicationDbContext(_options);
        _context.Database.OpenConnection(); // Keep in-memory DB alive
        _context.Database.EnsureCreated();
    }

    [TearDown]
    public void TearDown()
    {
        _context.Database.CloseConnection();
        _context.Dispose();
    }

    [Test]
    public async Task WeatherForecast_HasCorrectTableName()
    {
        // Given: A weather forecast
        var forecast = new WeatherForecast()
        {
            Date = DateOnly.FromDateTime(DateTime.Now),
            TemperatureC = 20,
            Summary = "Sunny"
        };

        _context.WeatherForecasts.Add(forecast);
        await _context.SaveChangesAsync();

        // When: Checking the table name in the database
        var connection = _context.Database.GetDbConnection();
        await connection.OpenAsync();
        using var command = connection.CreateCommand();
        command.CommandText = "SELECT name FROM sqlite_master WHERE type='table' AND name='YoFi.V3.WeatherForecasts'";
        var tableName = await command.ExecuteScalarAsync();

        // Then: The table should exist with the correct name
        Assert.That(tableName, Is.EqualTo("YoFi.V3.WeatherForecasts"));
    }

    [Test]
    public async Task WeatherForecast_IdIsAutoGenerated()
    {
        // Given: A weather forecast without an ID set
        var forecast = new WeatherForecast()
        {
            Date = DateOnly.FromDateTime(DateTime.Now),
            TemperatureC = 20,
            Summary = "Sunny"
        };

        Assert.That(forecast.Id, Is.EqualTo(0)); // Initially zero

        // When: Adding and saving the forecast
        _context.WeatherForecasts.Add(forecast);
        await _context.SaveChangesAsync();

        // Then: The ID should be auto-generated
        Assert.That(forecast.Id, Is.GreaterThan(0));
    }
}
