#
# ### Build + Deploy to Production (CD)
#
# The Continuous Deployment template (CD.yaml) builds the code
# and deploys it to the production environment. 
#
# Currently, this runs for every new commit to main branch. In
# the future, it will be triggered by new tags only.
#
# REQUIRED VARIABLES:
# - azureStaticAppApiToken
#

trigger:
  tags:
    include:
    - '*'

pr: none

variables:
- template: vars/vars-all.yaml
- template: vars/vars-ci.yaml

#
# Build & Test Stage
#

stages:
- stage: BuildTestStage
  displayName: 'Build & Test'

  jobs:
  - job: BuildTestJob
    displayName: 'Build & Test'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - template: steps/git-checkout-self.yaml
    - template: steps/use-dotnet-sdk.yaml
      parameters:
        version: '10.x'
    - template: steps/build-solution.yaml
    - template: steps/run-tests.yaml
    - template: steps/docker-compose-build.yaml
    - template: steps/docker-compose-up.yaml
    - template: steps/run-functional-tests.yaml
    - template: steps/build-nuxt.yaml
    - template: steps/publish-nuxt.yaml
    - template: steps/publish-web-archive.yaml

#
# Containerize & Functional Test Stage
#

- stage: ContainerizeFunctionalTest
  displayName: 'Containerize & Functional Test'
  dependsOn: BuildTestStage
  condition: succeeded()

  jobs:
  - job: ContainerizeFunctionalTestJob
    displayName: 'Containerize & Functional Test'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - template: steps/git-checkout-self.yaml
    - template: steps/docker-compose-build.yaml
    - template: steps/docker-compose-up.yaml
    - template: steps/run-functional-tests.yaml
    # TODO: - template: steps/docker-compose-push.yaml

#
# Deploy to Azure Stage
#

- stage: Deploy
  displayName: 'Deploy to Azure'
  dependsOn: ContainerizeFunctionalTest
  condition: succeeded()

  jobs:
  - job: Deploy Static Web App
    displayName: 'Deploy to Azure Static Web App'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - template: steps/deploy-static.yaml

  - job: Deploy App Service
    displayName: 'Deploy to Azure App Service'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - template: steps/deploy-app-service.yaml

#
# TODO: Functional test against the deployed instance
#

