#
# ### Continueous Integration (CI)
#
# Ensure that code successfully builds, and push to dockerhub
#

trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

variables:
- template: vars/vars-all.yaml
- template: vars/vars-ci.yaml

steps:
- template: steps/git-checkout-self.yaml
- template: steps/use-dotnet-sdk.yaml
  parameters:
    version: '10.x'
- template: steps/build-solution.yaml
- template: steps/run-tests.yaml
- template: steps/docker-compose-build.yaml
# - template: steps/run-functional-tests.yaml
- template: steps/build-nuxt.yaml
- template: steps/publish-nuxt.yaml
- template: steps/publish-web-archive.yaml
# - template: steps/docker-compose-push.yaml
# - template: steps/deploy-nuxt.yaml
# - template: steps/deploy-web.yaml
