using Microsoft.Extensions.Configuration;

DotNetEnv.Env.Load();
var builder = DistributedApplication.CreateBuilder(args);
var appInsightsConnectionString = builder.Configuration["APPLICATIONINSIGHTS_CONNECTION_STRING"];

var apiService = builder.AddProject<Projects.YoFi_V3_BackEnd>("backend")
    .WithHttpHealthCheck("/health")
    .WithEnvironment("APPLICATIONINSIGHTS_CONNECTION_STRING", appInsightsConnectionString ?? "")
    .WithEnvironment("APPLICATION__ENVIRONMENT", "Local");

// Note that the version of the frontend isn't super relevant
// when running locally, since the backend and frontend are built together.
// However, we set it here for consistency. In production, when the frontend
// is generated by the build process, we really want to know what version
// of the code was used to generate it.

builder.AddJavaScriptApp("frontend-nuxt", "../FrontEnd.Nuxt")
    .WithPnpm()
    .WithEnvironment("NUXT_PUBLIC_API_BASE_URL", apiService.GetEndpoint("http"))
    .WithEnvironment("NUXT_PUBLIC_SOLUTION_VERSION", "Aspire")
    .WithEnvironment("NUXT_PUBLIC_APPLICATION_INSIGHTS_CONNECTION_STRING", appInsightsConnectionString ?? "")
    .WithReference(apiService)
    .WithHttpEndpoint(port: 5173, env: "PORT")
    .WithHttpHealthCheck("/health")
    .WithExternalHttpEndpoints()
    .PublishAsDockerFile();

builder.Build().Run();
