using Microsoft.Extensions.Configuration;

var builder = DistributedApplication.CreateBuilder(args);

// TODO: Read from config file

var apiService = builder.AddProject<Projects.YoFi_V3_BackEnd>("backend")
    .WithHttpHealthCheck("/health")
//TODO:    .WithEnvironment("APPLICATIONINSIGHTS_CONNECTION_STRING", appInsightsConnectionString ?? "")
    .WithEnvironment("APPLICATION__ENVIRONMENT", "Local");

// Note that the version of the frontend isn't super relevant
// when running locally, since the backend and frontend are built together.
// However, we set it here for consistency. In production, when the frontend
// is generated by the build process, we really want to know what version
// of the code was used to generate it.

builder.AddNpmApp("frontend-nuxt", "../FrontEnd.Nuxt")
    .WithEnvironment("NUXT_PUBLIC_SOLUTION_VERSION", "Aspire")
// TODO:    .WithEnvironment("NUXT_PUBLIC_APPLICATIONINSIGHTS_CONNECTION_STRING", appInsightsConnectionString ?? "")
    .WithReference(apiService)
    .WithHttpEndpoint(port: 5173, env: "PORT")
    .WithExternalHttpEndpoints()
    .PublishAsDockerFile();

builder.Build().Run();
